# Site settings
title: 개발자 박하은
email: haileyhe01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://pullingoff.github.io"
phone: "0000"

theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/
  # resume:
  #   output: true
  #   permalink: /resume/:path/
  # project:
  #   output: true
  #   permalink: /projects/:path/

# Build settings
markdown: kramdown
future: true
timezone: Asia/Seoul

# plugins
# plugins:
# - jekyll-paginate 

# pagination:
#   enabled: true
#   category: 'blog'
#   permalink: /:num/
#   per_page: 7
#   sort_reverse: true
#   sort_field: 'date'
#   title: ':title'
#   trail:
#     before: 2
#     after: 2

# paginate: 10                  # 페이징 처리 개수
# paginate_path: "/page:num/"   # URL 규칙