# Site settings
title: 개발자 박하은
email: haileyhe01@gmail.com
github: pullingoff
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://pullingoff.github.io"
phone: "0000"

theme-path: theme-assets # path to header assets etc
# map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

# 여기다 쓰고 _case 같은 디렉토리 만들어서 거기다가 md 써야함
collections:
  resource:
    output: true
    permalink: /resource/:path/
  project:
    output: true
    permalink: /project/:path/
  cs:
    output: true
    permalink: /cs/:path/
  fe:
    output: true
    permalink: /fe/:path/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
future: true
timezone: Asia/Seoul
plugins:
  - jekyll-sitemap # 만약 다른 플러그인 쓰는데 이걸 뒤에 넣어야 그것까지 구글 검색됨