# Site settings
title: 일리헤
email: haileyhe01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "거미는  자신의 실로써  공간의 자유에  이른다. " <br/>
      좋아하는 책 중 하나인 ‘저지대’에 나오는 구절입니다. <br/>
    궁금한 것에 도전하고, 나아갈 방향을 탐구하는 제 모습이 거미와 같다고 느꼈습니다. <br/>
    마케팅을 전공하고 데이터 분석을 공부하다가 프로그래밍에 흥미를 느껴 개발을 본격적으로 배웠습니다.
    요즘은 파이썬과 프론트엔드를 열심히 공부하고 있습니다.
baseurl: ""
url: "https://hailey99.github.io"
phone: "0000"
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/
  resume:
    output: true
    permalink: /resume/:path/

# Build settings
markdown: kramdown